Repository OZ-Coding-School/oz_03_main-003-FE, pull requests merged in 2024-07, with the labels that each got.

#13 Feat: sns 로그인버튼 작업
  src/App.tsx
  src/components/button/ButtonEmoTree.tsx
  src/components/button/ButtonSignInGoogle.tsx
  src/components/button/ButtonSignInKakao.tsx
Labels: enhancement

#79 Confirm창 FX 추가 #56
  src/assets/sound/btn_confirm.mp3
  src/components/common/modal/ModalChangeName.tsx
  src/components/common/modal/ModalEditProfile.tsx
Labels: Feat

#82 감정 값 수동 조정 모달 추가
  src/api/admin.ts
  src/components/admin/AdminEmotion.tsx
  src/components/admin/AdminEmotionItem.tsx
  src/components/admin/AdminForestItem.tsx
  src/components/admin/AdminTreeItem.tsx
  src/components/common/modal/ModalAdminChangeEmotion.tsx
  src/config/types.ts
  src/pages/PageAdmin.tsx
Labels: Feat

#84 Badge 텍스트 컬러 변경, 감정 전달하기 기능 구현
  src/components/common/badge/BadgeAngry.tsx
  src/components/common/badge/BadgeHappy.tsx
  src/components/common/badge/BadgeIndifference.tsx
  src/components/common/badge/BadgeJoy.tsx
  src/components/common/badge/BadgeSorrow.tsx
  src/components/common/badge/BadgeWorry.tsx
  src/components/common/button/ButtonEmoTree.tsx
  src/components/common/dialog/DialogRoom.tsx
Labels: Feat, Style

#87 Feat: 랜딩페이지 구현중 #76
  src/assets/icon/icon-linestar.svg
  src/assets/images/landing-bg.png
  src/assets/images/landing-chat.svg
  src/assets/images/landing-forest01.svg
  src/assets/images/landing-forest02.svg
  src/assets/images/landing-forest03.svg
  src/assets/images/landing-ground.svg
  src/assets/images/landing-ground01.svg
  src/assets/images/landing-ground02.svg
  src/assets/images/landing-ground03.svg
  src/assets/images/landing-tree01.svg
  src/assets/images/landing-tree02.svg
  src/components/Landing.tsx
  src/config/IconData.tsx
  src/pages/PageAuth.tsx
Labels: Feat, Style

#88 랜딩페이지 작업 완료
  src/assets/icon/icon-blog.svg
  src/assets/icon/icon-gemini.svg
  src/assets/icon/icon-github.svg
  src/assets/icon/icon-line.svg
  src/assets/icon/icon-top-arw.svg
  src/components/Landing.tsx
  src/components/common/button/ButtonSignInGoogle.tsx
  src/components/common/home/HomeBg.tsx
  src/components/common/home/HomeChatInfo.tsx
  src/components/common/home/HomeCopyright.tsx
  src/components/common/home/HomeForestInfo.tsx
  src/components/common/home/HomeTeamInfo.tsx
  src/components/common/home/HomeTreeInfo.tsx
  src/config/IconData.tsx
Labels: Feat, Style
